//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.05 at 01:05:24 PM IST 
//


package com.mani.read1;

import javax.xml.bind.annotation.XmlRegistry;
import com.mani.read1.Root.Course;
import com.mani.read1.Root.Course.Place;
import com.mani.read1.Root.Course.Time;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mani.read1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mani.read1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Time }
     * 
     */
    public Time createRootCourseTime() {
        return new Time();
    }

    /**
     * Create an instance of {@link Course }
     * 
     */
    public Course createRootCourse() {
        return new Course();
    }

    /**
     * Create an instance of {@link Place }
     * 
     */
    public Place createRootCoursePlace() {
        return new Place();
    }

    /**
     * Create an instance of {@link Root }
     * 
     */
    public Root createRoot() {
        return new Root();
    }

}
