//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.05 at 10:25:49 AM IST 
//


package com.mani.resume;

import javax.xml.bind.annotation.XmlRegistry;
import com.mani.resume.Resumes.Person;
import com.mani.resume.Resumes.Person.Address;
import com.mani.resume.Resumes.Person.Project;
import com.mani.resume.Resumes.Person.Project.Client;
import com.mani.resume.Resumes.Person.Project.Keywords;
import com.mani.resume.Resumes.Person.Project.Position;
import com.mani.resume.Resumes.Person.Project.Staff;
import com.mani.resume.Resumes.Person.Project.Supervisor;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mani.resume package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mani.resume
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Supervisor }
     * 
     */
    public Supervisor createResumesPersonProjectSupervisor() {
        return new Supervisor();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createResumesPersonAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link Position }
     * 
     */
    public Position createResumesPersonProjectPosition() {
        return new Position();
    }

    /**
     * Create an instance of {@link Keywords }
     * 
     */
    public Keywords createResumesPersonProjectKeywords() {
        return new Keywords();
    }

    /**
     * Create an instance of {@link Client }
     * 
     */
    public Client createResumesPersonProjectClient() {
        return new Client();
    }

    /**
     * Create an instance of {@link Project }
     * 
     */
    public Project createResumesPersonProject() {
        return new Project();
    }

    /**
     * Create an instance of {@link Staff }
     * 
     */
    public Staff createResumesPersonProjectStaff() {
        return new Staff();
    }

    /**
     * Create an instance of {@link Resumes }
     * 
     */
    public Resumes createResumes() {
        return new Resumes();
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createResumesPerson() {
        return new Person();
    }

}
