//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.05 at 09:49:43 AM IST 
//


package com.mani.beans;

import javax.xml.bind.annotation.XmlRegistry;
import com.mani.beans.Letter.Address;
import com.mani.beans.Letter.Greetings;
import com.mani.beans.Letter.Logo;
import com.mani.beans.Letter.Salutation;
import com.mani.beans.Letter.Text;
import com.mani.beans.Letter.Text.Component;
import com.mani.beans.Letter.Title;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mani.beans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mani.beans
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Greetings }
     * 
     */
    public Greetings createLetterGreetings() {
        return new Greetings();
    }

    /**
     * Create an instance of {@link Logo }
     * 
     */
    public Logo createLetterLogo() {
        return new Logo();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createLetterAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link Component }
     * 
     */
    public Component createLetterTextComponent() {
        return new Component();
    }

    /**
     * Create an instance of {@link Salutation }
     * 
     */
    public Salutation createLetterSalutation() {
        return new Salutation();
    }

    /**
     * Create an instance of {@link Letter }
     * 
     */
    public Letter createLetter() {
        return new Letter();
    }

    /**
     * Create an instance of {@link Text }
     * 
     */
    public Text createLetterText() {
        return new Text();
    }

    /**
     * Create an instance of {@link Title }
     * 
     */
    public Title createLetterTitle() {
        return new Title();
    }

}
