//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.05 at 11:55:51 AM IST 
//


package com.mani.pom;

import javax.xml.bind.annotation.XmlRegistry;
import com.mani.pom.Project.Build;
import com.mani.pom.Project.Build.Plugins;
import com.mani.pom.Project.Build.Plugins.Plugin;
import com.mani.pom.Project.Build.Plugins.Plugin.Configuration;
import com.mani.pom.Project.Dependencies;
import com.mani.pom.Project.Dependencies.Dependency;
import com.mani.pom.Project.Developers;
import com.mani.pom.Project.Developers.Developer;
import com.mani.pom.Project.Licenses;
import com.mani.pom.Project.Licenses.License;
import com.mani.pom.Project.Properties;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mani.pom package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mani.pom
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Licenses }
     * 
     */
    public Licenses createProjectLicenses() {
        return new Licenses();
    }

    /**
     * Create an instance of {@link Properties }
     * 
     */
    public Properties createProjectProperties() {
        return new Properties();
    }

    /**
     * Create an instance of {@link Build }
     * 
     */
    public Build createProjectBuild() {
        return new Build();
    }

    /**
     * Create an instance of {@link Dependency }
     * 
     */
    public Dependency createProjectDependenciesDependency() {
        return new Dependency();
    }

    /**
     * Create an instance of {@link Developer }
     * 
     */
    public Developer createProjectDevelopersDeveloper() {
        return new Developer();
    }

    /**
     * Create an instance of {@link Dependencies }
     * 
     */
    public Dependencies createProjectDependencies() {
        return new Dependencies();
    }

    /**
     * Create an instance of {@link Configuration }
     * 
     */
    public Configuration createProjectBuildPluginsPluginConfiguration() {
        return new Configuration();
    }

    /**
     * Create an instance of {@link Project }
     * 
     */
    public Project createProject() {
        return new Project();
    }

    /**
     * Create an instance of {@link Plugin }
     * 
     */
    public Plugin createProjectBuildPluginsPlugin() {
        return new Plugin();
    }

    /**
     * Create an instance of {@link Developers }
     * 
     */
    public Developers createProjectDevelopers() {
        return new Developers();
    }

    /**
     * Create an instance of {@link License }
     * 
     */
    public License createProjectLicensesLicense() {
        return new License();
    }

    /**
     * Create an instance of {@link Plugins }
     * 
     */
    public Plugins createProjectBuildPlugins() {
        return new Plugins();
    }

}
